name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        mkdir -p ~/.ssh
        echo -n $SSH_PRIVATE_KEY >> ~/.ssh/blih
        chmod 400 ~/.ssh/blih
        cat -e ~/.ssh/blih | wc -c && echo toto
        echo $TEST
        echo test2
        echo test3
        echo -ne "Host git.epitech.eu\n\tHostname git.epitech.eu\n\tUser git\n\tIdentityFile $(readlink -f ~/.ssh/blih)\n" >> ~/.ssh/config
        git config --global user.email "tristan.roux@epitech.eu"
        git config --global user.name "Tristan Roux"
        ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts 
        git clone git@git.epitech.eu:/tristan.roux@epitech.eu/MUL_my_runner_2019 /tmp/blihRepo
        export REPOVAR=`pwd`
        cd /tmp/blihRepo
        find .  -not -path "./.git*" -delete
        cp -r $REPOVAR/* .
        git add -A
        git commit -m "Sync"
        git push origin master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TEST: ${{ secrets.TEST }}
