name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: | 
        mkdir -p ~/.ssh
        echo -ne $SSH_PRIVATE_KEY >> ~/.ssh/blih
        echo -ne "Host git.epitech.eu\n\tHostname git.epitech.eu\n\tUser git\n\tIdentityFile $(readlink -f ~/.ssh/blih)\n"
        git config --global user.email "tristan.roux@epitech.eu"
        git config --global user.name "Tristan Roux"
        ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts 
        git remote add blih ssh://git@git.epitech.eu/tristan.roux@epitech.eu/MUL_my_runnner_2019
        git push blih master:master
